Explicitly use UTF-8 encoding for Gradle
This is due to different encoding when building on Windows

C:\Users\Terezi Pyrope\AttestationServer\src\main\java\app\attestation\server\AttestationProtocol.java:241: error: unmappable character (0x81) for encoding windows-1252
    private static final String DEVICE_MOTO_G7 = "Motorola moto g�?�";
                                                                  ^

Signed-off-by: June <aobugene@reliaquest.com>